### ISSUE TITLE
change shithole date 

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#10]
We pushed the Shithole date back to 03/12/2017; could you adjust the listing?

**Comment by mglobel** [comment]
That damn there shithole. Made me gone forgot to close via a commit message: https://help.github.com/articles/closing-issues-via-commit-messages/

For posterity's sake, closed via: https://github.com/ashwednesday/rapashwednesday/commit/351e34c5943d433bdd7ffaa94d24d10d7e6f0f1e

💩
