### ISSUE TITLE
discuss incorporating video

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#13]
https://www.youtube.com/watch?v=0OvPe3Fqhg0 [shithole show]
https://www.youtube.com/watch?v=ONnReR8_NJk [new record teaser]
https://vimeo.com/205790871 [party in my backyard; protected w/ a password which is ashrocks]

i do have a youtube channel now; not sure how to link directly to it though; maybe this link will work: https://www.youtube.com/channel/UCkpcBvbeaTvPRxYCwdF-IFg

**Comment by mglobel** [comment]
continuing on #15
