### ISSUE TITLE
add video clips/youtube link

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#15]
probably putting clips directly on the site is too slow to be in line with the concept mobile first 

my youtube channel: https://www.youtube.com/channel/UCkpcBvbeaTvPRxYCwdF-IFg

**Comment by mglobel** [comment]
F yeeeeaaah mobile first. Plus probably wanna drive people to subscribe to that youtube social-ish. I'd say icon for YouTube on the social media bar and then a section on the home page that has a header and cta (call to action) pushing to follow/subscribe for the latest AshWednesday videos

**Comment by ashwednesday** [comment]
that icon in media bar + follow/subscribe sounds good to me

if we do a CTA section, then could have 'follow' for twitter there too?

**Comment by mglobel** [comment]
yeah i think that'd work. it'd just become a 'Follow Ash Wednesday' section, with twitter and youtube buttons. Twitter over instagram or snap?

**Comment by mglobel** [comment]
added youtube in icon row
