### ISSUE TITLE
replace Ugly on Purpose soundcloud listening with spotify

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#19]
so listens go through the service that pays! i think this will be the correct link:

https://open.spotify.com/album/2JFf60r7ChmBxijYEddSOJ

**Comment by ashwednesday** [comment]
more information:

https://developer.spotify.com/technologies/widgets/spotify-play-button/

**Comment by mglobel** [comment]
Nooooice! 💵 💸 🌟 

We can put the spotify widget where the soundcloud one is, and then maybe repurpose the latest singles section for the video section we were talking about...

Do we want to keep the soundcloud icon on the social bar?

**Comment by ashwednesday** [comment]
the repurposing of the singles section for videos sounds good to me, but didn't we decide putting videos on the site is in conflict with mobile first?

i do think we should keep the soundcloud icon on the social bar; could we add tidal, spotify, apple music?

**Comment by mglobel** [comment]
Hmm, maybe we break up the social bar into two parts? Otherwise it'll be a lot of logos on one line. Something like this perhaps...
```
Follow
Facebook | Twitter | Instagram | Snapchat (?_?)
Listen
Spotify | Apple | Tidal | Soundcloud | Youtube
````
And then the youtube section..i'll check out youtube's mobile embed, maybe it's aight. i definitely watch videos on the youtube mobile app. there may be a way to link on the mobile view to open in the youtube app if the person has it downloaded...otherwise, for mobile can just show a button with 'Follow on Youtube'

**Comment by mglobel** [comment]
p.s. updated shows list for Shit Hole show. hope it was boooooss! :business_suit_levitating:

**Comment by ashwednesday** [comment]
I like the idea of breaking the social bar into 2 parts (follow vs listen) & definitely into getting my snapchat on there ha!

have you had a chance to check in to the youtube mobile embed? i dont mind directing the user to this app, but likely i won't want them to be directed to another browser cause that's annoying. 

the button with the follow would do me nicely for now if the embed takes a second to figure; basically because we don't have much high quality video to show off at the moment

**Comment by ashwednesday** [comment]
closing this since some of it has been handled; i'll re-open a new issue about buttons:

1. follow buttons
2. listen buttons
3. youtube embed
