### ISSUE TITLE
create favicon

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#2]

**Comment by ashwednesday** [comment]
i like the idea of the shoe icon, but let me think more @mglobel

**Comment by ashwednesday** [comment]
![15672975_2850789826856_1636156079461120317_n](https://cloud.githubusercontent.com/assets/22849666/21487115/86dcfee4-cb87-11e6-8b52-3da6d4c140fd.jpg)

can u (or someone you know) make this into an icon?

**Comment by mglobel** [comment]
Quite possibly..Lemme investigate

**Comment by mglobel** [comment]
Favicon version!

<img width="450" alt="screen shot 2016-12-27 at 11 00 29 am" src="https://cloud.githubusercontent.com/assets/3036915/21504355/c5ec0c1e-cc23-11e6-8464-55835e8fc727.png">

Need to add to the main site and deploy, but that could work for starts. I kinda want to see what it looks like with rounded edges or even as a circle image..

But first I must attend a free flexibility consultation with a pilates/yoga/flex person that just moved into my building. Free 30 min one-on-one, why not?! 

🐣

**Comment by mglobel** [comment]
BTW, you can use emojis in github by wrapping certain words with `:`, e.g. `:100:`. Which prints out to 💯

**Comment by mglobel** [comment]
Alright @ashwednesday, i like that image as a favicon, only one question left, square or circle favicon:

## Circle
<img width="1029" alt="screen shot 2016-12-29 at 12 19 34 pm" src="https://cloud.githubusercontent.com/assets/3036915/21550658/47678f68-cdc1-11e6-909d-21e631ad484f.png">

## Square
<img width="892" alt="screen shot 2016-12-29 at 12 20 11 pm" src="https://cloud.githubusercontent.com/assets/3036915/21550662/51c01c82-cdc1-11e6-8ebc-7502a9e4cf35.png">

The choice is yours and yours alone
