### ISSUE TITLE
swap cole's and crane shows 

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#24]
i think the show coming soonest should be on top yea?

**Comment by mglobel** [comment]
hey sry i've been in denver! and traveling. but went to fix this and forgot i had some local work of a style stab at the redesign, from after our last sesh. So I deployed the show switch and accidentally deployed the style changes: https://rapashwednesday.com

Thoughts? it's on a "Branch", which is how we keep track of code changes on Github. I'll open a "Pull Request" where we can look at the changes and give a 👍 or undo.

**Comment by ashwednesday** [comment]
hey! the site doesn't look that much different to me. The changes I see are a different background color and different text color. Overall it still has that blocky feel we had wanted to trade for something more sophisticated. To change this let's first think about the fonts. It's all very square. Can we introduce some finesse?

1. let's elongate Ash Wedensday and give it a sexier font; something with a curve
2. move "about / shows / merch" further to the right and offset it 
3. remove the title "Ugly on Purpose"
4. replace that Ugly on Purpose cover art with this picture from my IG until I can get some globe ones taken: https://www.instagram.com/p/BOdFvNOg6i_/?taken-by=rapashwednesday
5. the list of shows could look better; maybe it's the alignment that has it looking like there's too much space and not enough information. let me think more on how to organize that

![example new site](https://user-images.githubusercontent.com/22849666/27592333-d1052fc4-5b19-11e7-8b52-8a5d1034e612.jpg)

the font is here: http://www.dafont.com/finesse.font

**Comment by ashwednesday** [comment]
i'll close this since some items have been taken care of; i'll open a new ticket for 1 & 2 above
