### ISSUE TITLE
new font || ash wednesday, about, shows, merch

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#27]
1. let's elongate Ash Wedensday and give it a sexier font; something with a curve
2. move "about / shows / merch" further to the right [or somehow offset it so it pops]

the font is here: http://www.dafont.com/finesse.font

[27592333-d1052fc4-5b19-11e7-8b52-8a5d1034e612.pdf](https://github.com/ashwednesday/rapashwednesday/files/1124984/27592333-d1052fc4-5b19-11e7-8b52-8a5d1034e612.pdf)

**Comment by ashwednesday** [comment]
hey @mglobel can you take a crack at the new font soon? xo

**Comment by mglobel** [comment]
@ashwednesday gettin on it now! only issue is finesse font is only free for personal use..i'm trying to see if there's a similar on https://fonts.google.com or www.fontsquirrel.com

**Comment by mglobel** [comment]
the display, handwriting category has some interesting ones: https://fonts.google.com/?category=Display,Handwriting

**Comment by mglobel** [comment]
@ashwednesday some other options

![screen shot 2017-07-24 at 4 45 59 pm](https://user-images.githubusercontent.com/3036915/28546228-99ca8244-708f-11e7-99df-ec3b3dc54bf8.png)


![screen shot 2017-07-24 at 4 45 33 pm](https://user-images.githubusercontent.com/3036915/28546211-8b3f8396-708f-11e7-9880-8d33e345ee0e.png)


![screen shot 2017-07-24 at 4 48 02 pm](https://user-images.githubusercontent.com/3036915/28546322-e3c0504a-708f-11e7-9d5e-55b84e3eec67.png)


![screen shot 2017-07-24 at 4 48 48 pm](https://user-images.githubusercontent.com/3036915/28546364-06c6b390-7090-11e7-9372-ace11a86449a.png)

**Comment by ashwednesday** [comment]
yeah i like the typeface you picked

**Comment by ashwednesday** [comment]
can you make the blue brighter and layer yellow underneath?

![27592333-d1052fc4-5b19-11e7-8b52-8a5d1034e612](https://user-images.githubusercontent.com/22849666/28593001-8548be46-7150-11e7-8a42-446692117b80.jpg)

**Comment by mglobel** [comment]
resolved on https://rapashwednesday-buzzbell-redesign.netlify.com/home
