### ISSUE TITLE
buttons || follow, listen, youtube embed

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#29]
ok i think i have a solution here! 

1. follow buttons will stay where they are now; under Ash Wednesday. 
a. let's have it: Facebook | Twitter | Instagram | Snapchat (?_?)
[ash current buttons.pdf](https://github.com/ashwednesday/rapashwednesday/files/1125141/ash.current.buttons.pdf)

2. listen buttons can be placed below the current project 
b. let's have it: Spotify | Apple | Tidal | Soundcloud | Youtube
[play bar.pdf](https://github.com/ashwednesday/rapashwednesday/files/1125047/play.bar.pdf)

3. once we make a video [on my to do list], then our youtube embed can live between current project and latest singles or replace the latest singles section altogether 

mglobel notes from the previous issue: [[i'll check out youtube's mobile embed, maybe it's aight. i definitely watch videos on the youtube mobile app. there may be a way to link on the mobile view to open in the youtube app if the person has it downloaded...otherwise, for mobile can just show a button with 'Follow on Youtube’]]

and here's that example of buttons for reference: ![26995391-fd7841e0-4d31-11e7-82d7-d427e1f8a472](https://user-images.githubusercontent.com/22849666/27869562-eb8a09ee-6165-11e7-8b1b-4d1ee77b3c3e.jpg)

**Comment by ashwednesday** [comment]
http://www.sabapivot.com/ some inspiration for breaking up the buttons comes from this site

**Comment by ashwednesday** [comment]
here's a screenshot of what i imagine the listen buttons will look like. they'd live right under the SoundCloud window

![sab buttons](https://user-images.githubusercontent.com/22849666/28676985-d03b6252-72b1-11e7-8790-39fed47bca39.jpg)

**Comment by mglobel** [comment]
Tracking on https://github.com/buzzbell/rapashwednesday/issues/3
