### ISSUE TITLE
center upcoming & past in shows section

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#31]
![upcoming past](https://user-images.githubusercontent.com/22849666/28631295-4b802058-71f2-11e7-9063-53d3c037f5fd.jpg)

**Comment by mglobel** [comment]
crikey, didn't notice past was so far off to the right! was just seeing the upcoming to the left, sorry that's been off for so long. pushing up a quick fix that has them centered, but the columns of upcoming and past aren't equal. working on the re-write for the content editable version now, so i'll make sure to address both in that

<img width="889" alt="screen shot 2017-08-18 at 6 20 45 pm" src="https://user-images.githubusercontent.com/3036915/29480939-fc4db5a6-8441-11e7-96f4-c8cceeaf7ac5.png">
