### ISSUE TITLE
Create a storyblok account

### ISSUE THREAD

**Issue by mglobel** [ashwednesday/rapashwednesday#32]
Hey @ashwednesday, the content-editable version of the site is under construction! when you get a chance, make an account here: https://www.storyblok.com/ and let me know. Then I can invite you to  the project.

**Comment by ashwednesday** [comment]
hey! i created an account at that website. the associated email address is rapashwednesday@gmail.com

**Comment by mglobel** [comment]
cool, you should have access now! still getting things setup, but you can see an example of editing some content here: http://app.storyblok.com/#!/me/spaces/40969/stories/50534

**Comment by mglobel** [comment]
you'll notice though @ashwednesday that the events automatically go into upcoming or past based on the date..so that's great! Solves #14 once it's released

styling's a little messed up just fyi, working with a friend to get a better way to render the shows so that the columns are always equal width for upcoming and past (right now they're not equal width on rapashwednesday.com)
