### ISSUE TITLE
tease upcoming record with new image

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#33]
![img_0020](https://user-images.githubusercontent.com/22849666/29599435-3c0561b6-8795-11e7-9baf-11d73778b218.JPG)

i want to add this image to the site somehow. maybe to the left of my face?

**Comment by mglobel** [comment]
i like the image! real clean. let me see if i can work it in to the new site. hope to launch that in the next week or so

**Comment by mglobel** [comment]
New site is coming along! Style is still bare bones, just getting the components in place. But it's kind of a nice tabula rosa opportunity. Most important part though is you can update the content! Try it out here: http://app.storyblok.com/#!/me/spaces/40969/stories/50534/blok/53367a16-75fc-4537-9e29-97d3de1e0d8e?s=1
