### ISSUE TITLE
add location for bio

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#4]

**Comment by ashwednesday** [comment]
Ash Wednesday & The Heroic Dose are best known for their obscure sample game, rich melodies, and most of all, Ash Wednesday’s fuck-you-nicely lyricism. Her verbose rhymes take on themes of power, social control, and self-rule, all while keeping the floor jumping. The Heroic Dose—comprised of Mike Balish on keyboard and Joel Handley on drums—bring a level of musicality to the game that’s seldom heard in hip-hop. Though their music defies genre (jazz hop? rock & rap?), they’re doing it with swag to spare. 


Though Ash has been talking shit and taking names since day one, she’s been doing it with a band behind her since 2012. Ash got into rapping in 2010 after a long fascination with the art form, which she discovered around age 12. Her first appearances on stage in Chicago were at Subterranean Lounge’s 606 Freestyle Open Mic where she earned her moniker Ash Wednesday.
 
During a show with her band at local venue Moe’s Tavern in 2014, Mike Balish (a childhood friend of Joel Handley’s), approached the band after their performance and in a priceless display of no-fucks-given, asked “where’s the fucking melody?” Those balls landed him a spot on the team and the Heroic Dose was born.
 
Ash Wednesday & The Heroic Dose have played venues across Chicago including Tonic Room, Township, @North Bar, and Quenchers. They’ve played alongside acts like Tomorrow Kings, Rich Jones, and Pivot Gang members MFN Melo, Squeak PIVOT, and dinnerwithjohn. In 2015 they released a project called Ugly on Purpose.

**Comment by mglobel** [comment]
Hmmm, yeah we'll need a spot to put this..Could be on the page, under the latest tracks or shows, or a separate page e.g. `/about` (maybe with some photos on it) and then we link to that somewhere

**Comment by mglobel** [comment]
@ashwednesday here's a version with the about on the homepage. thoughts?

http://psychiatrist-compass-47306.netlify.com/

**Comment by ashwednesday** [comment]
i like the about me on the homepage, but i wonder if people will know to scroll down to find it

could we add an "about" button up top of the page that would scroll the user down to the about section?
