### ISSUE TITLE
add a repository for event RSVPs

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#5]
want to be able to send a link to a form where people can RSVP for an event, then collect those forms on the back end for review

**Comment by mglobel** [comment]
Hey @ashwednesday, what's the priority on this one? Is this something you were hoping for the Dec. 29 event?

Second question, what fields were you thinking? Just email, or some other things like name, etc.

**Comment by ashwednesday** [comment]
hey! @mglobel -- low priority here; I don't need it for 12/29

fields: email, first name & last name (?), # attending

**Comment by ashwednesday** [comment]
[bobby raps rsvp example.pdf](https://github.com/ashwednesday/rapashwednesday/files/669713/bobby.raps.rsvp.example.pdf)
[bobby raps forms example https-:docs.google.com:forms:.pdf](https://github.com/ashwednesday/rapashwednesday/files/669716/bobby.raps.forms.example.https-.docs.google.com.forms.pdf)

RSVP example

**Comment by mglobel** [comment]
Tracking on: https://github.com/buzzbell/rapashwednesday/issues/2
