### ISSUE TITLE
clean up site preview on facebook

### ISSUE THREAD

**Issue by ashwednesday** [ashwednesday/rapashwednesday#8]
so when i post a link to the site on facebook it pulls content from the show listings and is a bit hard to read. any way to switch this up?

[site on facebook.pdf](https://github.com/ashwednesday/rapashwednesday/files/686427/site.on.facebook.pdf)

side note: is this worth thinking about for other sites?

**Comment by mglobel** [comment]
this one's eaaasy, should have fixed long ago. What should it say? Here's a thing put together from the about paragraph:

"The official website for Ash Wednesday & The Heroic Dose. Chicago hip-hop with a mix of (jazz hop? rock & rap?), and swag to spare."

I just got caught with this on a cpl other sites. Must always remember to include meta description tag. e.g. `<meta name="description" content="This is a description that shows up as preview text on your site for facebook and search engines">`

**Comment by ashwednesday** [comment]
Let's have it say --

**Comment by ashwednesday** [comment]
Let's have it say -- 

"Official home of Ash Wednesday & The Heroic Dose - Chicago based alternative hip hop"
